### PR TITLE
Homework 04-04

### PR DESCRIPTION
**Pull request by wawasho**
comfortability: 4,
completeness: 4,
questions: 

My bootstrap css is not deploying to heroku. I tried several config file tweaks (which you can see in my 'troubleshooting' branch), tried different placements for the css files (ex: in the assets folder, in the public folder, in the public/assets folder) as well as what Heroku recommended but I can't get get it to work.

### CODE REVIEW

**Comment by wawasho** [comment]
Also, I couldn't get my tests passing without the hardcoded data.

**Comment by wawasho** [comment]
I cloned a repo from a screencast (on a separate directory) and after that rspec won't load and the app isn't working.

**Comment by rgpass** [comment]
This PR is almost empty. I'll need to review it on your computer.

**Comment by rgpass** [comment]
> My bootstrap css is not deploying to heroku. I tried several config file tweaks (which you can see in my 'troubleshooting' branch), tried different placements for the css files (ex: in the assets folder, in the public folder, in the public/assets folder) as well as what Heroku recommended but I can't get get it to work.

We will be covering how to deploy to Heroku with Rails.

**Pull request closed without merging**
